### ISSUE TITLE
Non-Instructors can log in

### ISSUE THREAD

**Issue by spdvi** [Zenonperez/2DAM-DI#2]
The app is not checking if a user is an instructor or not. This is an application only for instructors. Also, there's exception:
![image](https://github.com/Zenonperez/2DAM-DI/assets/62358226/92765b57-141d-400e-aa96-07c2400b559e)
You should update the methods of DataAccess with the newest ones, and also the database with the latest .bacpac.

**Comment by Zenonperez** [comment]
solved
